api:
  host: adguard.example.com
  proto: http
  username: admin
  passwd: admin

ping_jobs:
  - job:
      domain: server.lan
      interval: 60
      count: 4
      timeout: 2
      answers:
        primary: 10.0.0.1
        failover:
          - 10.0.0.2
          - 10.0.0.3
  - job:
      domain: server2.lan
      interval: 60
      count: 4
      timeout: 2
      answers:
        primary: 10.0.1.1
        failover:
          - 10.0.1.2
          - 10.0.1.3

http_jobs:
  - job:
      domain: example.lan
      interval: 10
      status: 200
      proto: http
      answers:
        primary: 10.0.2.1
        failover:
          - 10.0.2.2
